
stages:
  - build

variables:  
  GL_IMAGE: registry.gitlab.com/roninen/docker-hello-world:$CI_COMMIT_SHA
  COMMIT_IMAGE: roninen/docker-hello-world:$CI_COMMIT_TAG
  LATEST_IMAGE: roninen/docker-hello-world:latest

services:
  - docker:dind
    
contain:
  stage: build
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $GL_IMAGE .
    - docker tag $GL_IMAGE $COMMIT_IMAGE
    - docker tag $GL_IMAGE $LATEST_IMAGE
    - docker push $GL_IMAGE
