sudo: required

install: true

services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

install: true

script: true

after_success:
  - docker --version
  - docker build -t hello-world .
  - docker push roninen/hello-world:latest

language: go
